name = "little-parcel"
compatibility_date = "2026-08-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "PARCELS"
database_name = "little-parcel-db"
database_id = "bc638a8e-23cb-4435-94ed-850f3ffefb98"
